### PR TITLE
a few more fixes

### PR DESCRIPTION
**Pull request by fchapoton**
so that both files can be imported cleanly in python 3

### CODE REVIEW

**Review by princengoc — CHANGES_REQUESTED** [review]
Thanks for contributing. Could you kindly use black to reformat? I know that this is pretty old codes, but  since this is a cosmetic fix one may as well use a modern and automatic tool to standardize.

**Comment by fchapoton** [comment]
Voilà. Done

**Review by princengoc — APPROVED** [review]
thanks!

**Comment by fchapoton** [comment]
so this is ready to merge ?

**Comment by princengoc** [comment]
Ah, yes done. Sorry I didn't realize that you couldn't merge (duh!). If you'd like I'm happy to add you as a collaborator on this repo. (May I ask what are you using this for? This code is pretty old so I'm happy that someone is finding some uses for it).

**Pull request merged**
